### ISSUE TITLE
Docker without pandas

### ISSUE THREAD

**Issue by pixuenan** [ssadedin/ximmer#19]
Hello, 

When I run ximmer docker at the final stage to consolidate reports, I get this error
```
Ximmer	[1]	INFO	|7:53:07 Executing python script ... 
Traceback (most recent call last):
  File "/usr/local/ximmer/src/main/python/cnv_size_histogram.py", line 2, in <module>
    import pandas as pd
ImportError: No module named pandas
Caught: java.lang.RuntimeException: Execution of python script /./.ximmertmp/4342302419878666-0/XimmerPythonScript.sh failed:
```
Seems the docker need pandas to run properly.

**Comment by ssadedin** [comment]
Thanks for mentioning this - I will try and reproduce and update the container. Not sure how I ran it successfully previously without pandas installed.

**Comment by pixuenan** [comment]
Hi Simon,

Thanks for your reply. Sorry for create this issue, after a close check with the build process of the docker image, I found the installation of pandas was failed. So my docker image was created "successfully" without pandas.
